### ISSUE TITLE
heapexp is missing

### ISSUE THREAD

**Issue by m1ghtym0** [SeanHeelan/HeapLayout#1]
It seems like there is a module missing in the git:
```
Traceback (most recent call last):
  File "./runexp.py", line 12, in <module>
    from heapexp import logutils, startgen, interactiongen, executor, drivers
ModuleNotFoundError: No module named 'heapexp'
```

**Comment by SeanHeelan** [comment]
Hey, sorry for the delay in addressing this. Busy post USENIX ;) Let me know if you have any other issues. You'll need to add the `Sieve` directory to your PYTHONPATH.
